name: Build

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 1 * * 1'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Build container
        run: podman build -t ghcr.io/charles8191/netherite/9 .
      - name: Push container
        run: podman push ghcr.io/charles8191/netherite/9
